name: "Flujo CD"
on:
  workflow_dispatch:
 #   inputs:
 #     cloud:
 #       description: "Proveedor Cloud"
 #       required: true
 #       default: "AWS"
 #        options: ["AWS", "GCP", "Azure"]
jobs:
  azure:
    runs-on: ubuntu-latest
    if: github.event.inputs.cloud == 'Azure'
    steps:
      - name: "Autenticar en Azure"
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 #v1 #v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Crear Azure Container Instance"
        uses: Azure/aci-deploy@28cafb864979bc5b44cd1f3fd45522727eb5a3db #v1 #v1.1.3
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_NAME }}
          name: ${{ vars.AZURE_CONTAINER_INSTANCE_NAME }}
          dns-name-label: ${{ vars.AZURE_DNS }}
          image: ${{ vars.AZURE_REGISTRY_NAME }}/${{ vars.AZURE_IMAGE_NAME }}:latest
          registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          location: ${{ vars.AZURE_REGION }}
