name: Deploy
run-name: Deploy EC2 insta
on:
 push:
   branches:
      - main
jobs:
  EC2-deploy:
   run-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Deploying an instance
       with:
         aws_access_key_id: ${{secret.AWS_ACCES_KEY_ID}}
         aws_secret_acces_key: ${{secret.AWS_SECRET_ACCES_KEY}}
         aws_defautl_region: us-east-1
         ami: ami-0357689e4fccbcd3 
         